# Kernel compile workflow for personal usage
# By Sarthak Roy (sarthakroy2002@gmail.com)

name: Kernel CI

on:
  workflow_dispatch:
    inputs:
      repo:
          description: 'Kernel source link'
          required: true
      branch:
          description: 'Kernel source branch'
          required: true   

env:
  TZ: Asia/Kolkata
  REPO: https://github.com/UtsavBalar1231/kernel_xiaomi_sm8250
  BRANCH: android12-next
  token: ${{ secrets.TOKEN }}
  chat_id: ${{ secrets.CHAT_ID }}

jobs:
  kernel-build:
    runs-on: ubuntu-22.04

    steps:



      - name: Initializing environment
        run: |
          git config --global user.name "comnerl123"
          git config --global user.email "stb.dandoank"
          sudo apt update
          sudo apt install -y bc bison build-essential ccache curl flex g++-multilib gcc-multilib binutils-aarch64-linux-gnu git gnupg gperf imagemagick lib32ncurses5-dev lib32readline-dev lib32z1-dev liblz4-tool libncurses5 libncurses5-dev libsdl1.2-dev libssl-dev libwxgtk3.0-gtk3-dev libxml2 libxml2-utils lzop pngcrush rsync schedtool squashfs-tools xsltproc zip zlib1g-dev python2 tmate ssh neofetch



      - name: Lets compile
        run: |
          git clone $REPO -b $BRANCH kernel 
          git clone https://github.com/UtsavBalar1231/Anykernel3 --depth=1 -b kona anykernel
          git clone https://android.googlesource.com/platform/prebuilts/gas/linux-x86/ -b master --depth=1 gas
          git clone https://gitlab.com/ThankYouMario/android_prebuilts_clang-standalone/ -b 11 --depth=1 clang
          cd kernel
          bash scripts/build_kernel --aosp-clang --os-MIUI --devices-umi
          #wget  https://raw.githubusercontent.com/AbzRaider/kernel_build_scripts/main/Kernel/RM6785_build_script.sh
          bash RM6785_build_script.sh
